name: baseImageBuild

on:
  push:
    branches: [ main ]

jobs:
  baseImageBuild:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Normalize repository name
        run: |
          echo "REPOSITORY_LOWERCASE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build robot-farm-base
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/robotFarm-ubuntu.dockerfile
          target: robot-farm-base
          push: true
          tags: ghcr.io/${{ env.REPOSITORY_LOWERCASE_NAME }}:base-${{ github.sha }}
          cache-from: type=registry,mode=max,ref=ghcr.io/${{ env.REPOSITORY_LOWERCASE_NAME }}:buildcache
          cache-to: type=registry,mode=max,ref=ghcr.io/${{ env.REPOSITORY_LOWERCASE_NAME }}:buildcache
