name: robotFarmBase

on:
  push:
    branches: [ main ]

jobs:
  baseBuild:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/robotFarm-ubuntu.dockerfile
          target: robot-farm-base
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/robot-farm:base-${{ github.sha }}
          cache-to: type=registry,mode=max,ref=ghcr.io/${{ github.repository }}:buildcache
