name: docker-image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main

jobs:
  base-stage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os_base:
          - name: ubuntu:22.04
            image: ghcr.io/ajakhotia/infracommons/weekly/ubuntu:22.04
          - name: ubuntu:24.04
            image: ghcr.io/ajakhotia/infracommons/weekly/ubuntu:24.04

    steps:
      - name: self-checkout
        id: self-checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: setup-login
        id: setup-login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup-buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v4

      - name: job-cache-base
        id: job-cache-base
        uses: ./external/infraCommons/.github/actions/oci-compliant-image-name
        with:
          build-name: job-cache/${{ matrix.os_base.name }}/base

      - name: image-name-base
        id: image-name-base
        uses: ./external/infraCommons/.github/actions/oci-compliant-image-name
        with:
          build-name: ${{ matrix.os_base.name }}/base

      - name: base
        id: base
        uses: ./external/infraCommons/.github/actions/docker-typical-build-push
        with:
          dockerfile: docker/ubuntu.dockerfile
          target-stage: base
          cache-backend: registry
          image-name: ${{ steps.image-name-base.outputs.name }}
          shared-cache-to: ${{ steps.job-cache-base.outputs.name }}:cache
          build-args: |
            OS_BASE=${{ matrix.os_base.image }}


  aggregate-base-stage:
    name: aggregate-base-stage
    if: always()
    needs: [base-stage]
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        id: self-checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: aggregate
        id: aggregate
        uses: ./external/infraCommons/.github/actions/matrix-aggregate
        with:
          result: ${{ needs.base-stage.result }}


  build-deploy-stage:
    needs: base-stage
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        os_base:
          - name: ubuntu:22.04
            image: ghcr.io/ajakhotia/infracommons/weekly/ubuntu:22.04
          - name: ubuntu:24.04
            image: ghcr.io/ajakhotia/infracommons/weekly/ubuntu:24.04
        toolchain:
          - linux-clang-19
          - linux-gnu-14
          - linux-gnu-default
        exclude:
          - os_base:
              name: ubuntu:22.04
            toolchain: linux-gnu-14

    steps:
      - name: self-checkout
        id: self-checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: setup-login
        id: setup-login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup-buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v4
        with:
          name: robotfarm-buildx
          keep-state: true

      - name: job-cache-base
        id: job-cache-base
        uses: ./external/infraCommons/.github/actions/oci-compliant-image-name
        with:
          build-name: job-cache/${{ matrix.os_base.name }}/base

      - name: image-name-build
        id: image-name-build
        uses: ./external/infraCommons/.github/actions/oci-compliant-image-name
        with:
          build-name: ${{ matrix.os_base.name }}/${{ matrix.toolchain }}/build

      - name: build
        id: build
        uses: ./external/infraCommons/.github/actions/docker-typical-build-push
        with:
          dockerfile: docker/ubuntu.dockerfile
          target-stage: build
          cache-backend: registry
          image-name: ${{ steps.image-name-build.outputs.name }}
          shared-cache-from: ${{ steps.job-cache-base.outputs.name }}:cache
          build-args: |
            OS_BASE=${{ matrix.os_base.image }}
            TOOLCHAIN=${{ matrix.toolchain }}

      - name: image-name-deploy
        id: image-name-deploy
        uses: ./external/infraCommons/.github/actions/oci-compliant-image-name
        with:
          build-name: ${{ matrix.os_base.name }}/${{ matrix.toolchain }}/deploy

      - name: deploy
        id: deploy
        uses: ./external/infraCommons/.github/actions/docker-typical-build-push
        with:
          dockerfile: docker/ubuntu.dockerfile
          target-stage: deploy
          cache-backend: registry
          image-name: ${{ steps.image-name-deploy.outputs.name }}
          build-args: |
            OS_BASE=${{ matrix.os_base.image }}
            TOOLCHAIN=${{ matrix.toolchain }}


  aggregate-build-deploy-stage:
    name: aggregate-build-deploy-stage
    if: always()
    needs: [build-deploy-stage]
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        id: self-checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: aggregate
        id: aggregate
        uses: ./external/infraCommons/.github/actions/matrix-aggregate
        with:
          result: ${{ needs.build-deploy-stage.result }}


  find-library:
    needs: build-deploy-stage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os_base:
          - name: ubuntu:22.04
            image: ghcr.io/ajakhotia/infracommons/weekly/ubuntu:22.04
          - name: ubuntu:24.04
            image: ghcr.io/ajakhotia/infracommons/weekly/ubuntu:24.04
        toolchain:
          - linux-clang-19
          - linux-gnu-14
          - linux-gnu-default
        exclude:
          - os_base:
              name: ubuntu:22.04
            toolchain: linux-gnu-14
        library-name:
          - absl
          - AMD
          - Boost
          - CAMD
          - CapnProto
          - CCOLAMD
          - Ceres
          - CHOLMOD
          - COLAMD
          - Eigen3
          - flatbuffers
          - Gflags
          - Glog
          - GTest
          - nlohmann_json
          - oatpp
          - oatpp-websocket
          - OGRE
          - OpenCV
          - protobuf
          - Python3
          - spdlog
          - SPQR
          - SuiteSparse_config
          - VTK

    steps:
      - name: self-checkout
        id: self-checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: setup-login
        id: setup-login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker-metadata
        id: docker-metadata
        uses: docker/metadata-action@v6
        with:
          tags: |
            type=sha,format=long

      - name: image-name-deploy
        id: image-name-deploy
        uses: ./external/infraCommons/.github/actions/oci-compliant-image-name
        with:
          build-name: ${{ matrix.os_base.name }}/${{ matrix.toolchain }}/deploy

      - name: find-library
        id: find-library
        uses: ./external/infraCommons/.github/actions/cmake-find-package
        with:
          library-name: ${{ matrix.library-name }}
          prefix-path: "/opt/robotFarm"
          image-name: ${{ steps.image-name-deploy.outputs.name }}:${{ steps.docker-metadata.outputs.version }}


  aggregate-find-library:
    name: aggregate-find-library
    if: always()
    needs: [find-library]
    runs-on: ubuntu-latest
    steps:
      - name: self-checkout
        id: self-checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: aggregate
        id: aggregate
        uses: ./external/infraCommons/.github/actions/matrix-aggregate
        with:
          result: ${{ needs.find-library.result }}
