name: infra-congruency-check

on:
  schedule:
    - cron: '0 0,12 * * *'
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main

jobs:
  congruency-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-self
        uses: actions/checkout@v5
        with:
          path: ${{ github.event.repository.name }}

      - name: checkout-infra-commons
        uses: actions/checkout@v5
        with:
          repository: ajakhotia/infraCommons
          path: infraCommons
          ref: main

      - name: congruency-test
        run: python3 infraCommons/ci/congruency_test.py -t infraCommons -c ${{ github.event.repository.name }} --apply-diffs

      - name: check-diffs
        id: check-diffs
        run: |
          cd ${{ github.event.repository.name }}
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: create-pull-request
        if: steps.check-diffs.outputs.has_changes == 'true'
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          cd ${{ github.event.repository.name }}
          branch_name="automated-update-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $branch_name

          # Commit and push changes
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Automated changes"
          git push origin $branch_name

          gh pr create \
          --base main \
          --head $branch_name \
          --title "Automated Update" \
          --body "This PR was automatically created by infraFilesCongruencyCheck GitHub Action to ensure that
                  core infra files remain synchronized with ajakhotia/infraCommons" \
