name: libraryBuild

on:
  workflow_run:
    workflows: ["baseImageBuild"]
    types: [completed]

jobs:
  libraryBuild:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        build_list:
          - AtlasExternalProject
          - BoostExternalProject
          - CapnprotoExternalProject
          - CerealExternalProject
          - CeresSolverExternalProject
          - Eigen3ExternalProject
          - FlatBuffersExternalProject
          - GFlagsExternalProject
          - GlogExternalProject
          - GoogleTestExternalProject
          - NlohmannJsonExternalProject
          - OatppExternalProject
          - OatppWebSocketExternalProject
          - OgreExternalProject
          - OpenCVExternalProject
          - ProtobufExternalProject
          - Python3ExternalProject
          - SpdLogExternalProject
          - SuiteSparseExternalProject
          - VTKExternalProject

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Normalize repository name
        run: |
          echo "REPOSITORY_LOWERCASE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build ${{ matrix.build_list }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/robotFarm-ubuntu.dockerfile
          target: robot-farm
          push: false
          cache-from: type=registry,mode=max,ref=ghcr.io/${{ env.REPOSITORY_LOWERCASE_NAME }}:buildcache
          build-args: |
            BUILD_LIST=${{ matrix.build_list }}
