name: External library builds

on:
  push:
    branches: [ main ]

jobs:
  externalLibraryBuild:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        os_base:
          - ubuntu:20.04
          - ubuntu:22.04
        toolchain:
          - linux-clang-12
          - linux-gnu-10
        build_list:
          - GoogleTestExternalProject
          - NlohmannJsonExternalProject

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Normalize repository name
        run: |
          echo "REPOSITORY_LOWERCASE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build ${{ matrix.build_list }} on ${{ matrix.os_base }} with ${{ matrix.toolchain }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/robotFarm-ubuntu.dockerfile
          target: robot-farm
          push: false
          cache-from: type=registry,mode=max,ref=ghcr.io/${{ env.REPOSITORY_LOWERCASE_NAME }}:buildcache
          build-args: |
            BUILD_LIST=${{ matrix.build_list }}
            BASE_IMAGE=${{ matrix.os_base }}
            TOOLCHAIN=${{ matrix.toolchain }}
