name: robot-farm

on:
  workflow_run:
    workflows: [ "robot-farm-base" ]
    types: [ completed ]

jobs:
  image-build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        os_base:
          - ubuntu:22.04
          - ubuntu:24.04
        toolchain:
          - linux-clang-19
          - linux-gnu-12
          - linux-gnu-14
        exclude:
          - os_base: "ubuntu:22.04"
            toolchain: linux-gnu-14
          - os_base: "ubuntu:24.04"
            toolchain: linux-gnu-12

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: setup-buildx
        uses: docker/setup-buildx-action@v3

      - name: setup-login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: normalize-repository-name
        id: normalize-repository-name
        uses: ./.github/actions/normalize
        with:
          string: ${{ github.repository }}

      - name: normalize-os-name
        id: normalize-os-name
        uses: ./.github/actions/normalize
        with:
          string: ${{ matrix.os_base }}

      - name: docker-metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.normalize-repository-name.outputs.string }}-${{ steps.normalize-os-name.outputs.string }}-${{ matrix.toolchain }}
          tags: |
            type=raw,value=${{ github.event.workflow_run.head_sha }}
            type=raw,value=latest,enable=${{ github.event.workflow_run.head_branch == 'main' }}

      - name: robot-farm
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/robotFarm-ubuntu.dockerfile
          target: robot-farm
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          cache-from: |
            type=registry,mode=max,ref=ghcr.io/${{ steps.normalize-repository-name.outputs.string }}-base-${{ steps.normalize-os-name.outputs.string }}:buildcache
            type=registry,mode=max,ref=ghcr.io/${{ steps.normalize-repository-name.outputs.string }}-${{ steps.normalize-os-name.outputs.string }}-${{ matrix.toolchain }}:buildcache
          cache-to: |
            type=registry,mode=max,ref=ghcr.io/${{ steps.normalize-repository-name.outputs.string }}-${{ steps.normalize-os-name.outputs.string }}-${{ matrix.toolchain }}:buildcache
          build-args: |
            BASE_IMAGE=${{ matrix.os_base }}
            TOOLCHAIN=${{ matrix.toolchain }}
