name: robot-farm-base

on:
  push:
    branches: [ main ]

jobs:
  base-image-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os_base:
          - ubuntu:22.04
          - ubuntu:24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-buildx
        uses: docker/setup-buildx-action@v3

      - name: setup-login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: normalize-repository-name
        id: normalize-repository-name
        uses: ./.github/actions/normalize
        with:
          string: ${{ github.repository }}

      - name: normalize-os-name
        id: normalize-os-name
        uses: ./.github/actions/normalize
        with:
          string: ${{ matrix.os_base }}

      - name: docker-metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.normalize-repository-name.outputs.string }}-base-${{ steps.normalize-os-name.outputs.string }}
          tags: |
            type=raw,value=${{ github.sha }}
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}

      - name: robot-farm-base
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/robotFarm-ubuntu.dockerfile
          target: robot-farm-base
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          cache-from: |
            type=registry,mode=max,ref=ghcr.io/${{ steps.normalize-repository-name.outputs.string }}-base-${{ steps.normalize-os-name.outputs.string }}:buildcache
          cache-to: |
            type=registry,mode=max,ref=ghcr.io/${{ steps.normalize-repository-name.outputs.string }}-base-${{ steps.normalize-os-name.outputs.string }}:buildcache
          build-args: |
            BASE_IMAGE=${{ matrix.os_base }}
