name: validate-library-install-template

on:
  workflow_call:
    inputs:
      os_base:
        description: 'Base image, e.g. ubuntu:22.04'
        required: true
        type: string
      toolchain:
        description: 'Toolchain, e.g. linux-gnu-12'
        required: true
        type: string
      library_name:
        description: 'Library to test (e.g. Eigen3)'
        required: true
        type: string
      image_tag:
        description: 'Image tag to pull (e.g. head SHA from imageBuild)'
        required: true
        type: string

jobs:
  validate-library-install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-self
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: checkout-import-tester
        uses: actions/checkout@v4
        with:
          repository: ajakhotia/importTester
          path: importTester
          ref: main

      - name: setup-login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: normalize-repository-name
        id: normalize-repository-name
        uses: ./.github/actions/normalize
        with:
          string: ${{ github.repository }}

      - name: normalize-os-name
        id: normalize-os-name
        uses: ./.github/actions/normalize
        with:
          string: ${{ inputs.os_base }}

      - name: docker-metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.normalize-repository-name.outputs.string }}-${{ steps.normalize-os-name.outputs.string }}-${{ matrix.toolchain }}
          tags: |
            type=raw,value=${{ github.sha }}

      - name: pull-robot-farm-image
        run: |
          docker pull ${{ steps.docker-metadata.outputs.tags }}

      - name: import-test
        run: |
          docker run --rm --volume ./importTester:/tmp/importTester ${{ steps.docker-metadata.outputs.tags }} bash -c \
            " \
              cd /tmp && \
              ls -lart /opt/robotFarm && \
              cmake --version && \
              cmake -E make_directory build && \
              cmake -S importTester -B build -DCMAKE_PREFIX_PATH=/opt/robotFarm -DIMPORT_TESTER_PACKAGE_LIST="Eigen3" \
          "
